export const teamPlay = [
  '소통 스타일',
  '협업 성향',
  '말하는 방식',
  '문제 해결방식',
  'MBTI',
];

export const teamPlayOptionList: { id: string; label: string }[] = [
  // 1 소통 스타일
  { id: 'CLEAR_AND_CONCISE', label: '명쾌하게 한마디로' },
  { id: 'OBSERVANT', label: '눈치 보는 스타일' },
  { id: 'RELAXED', label: '느긋한 편' },
  { id: 'DYNAMIC', label: '다이나믹 소통' },
  { id: 'HUMOROUS', label: '유머러스한 스타일' },
  { id: 'SERIOUS_AND_DEEP', label: '진지하게 깊이 있는' },
  { id: 'FAST_AND_SIMPLE', label: '빠르고 간결하게' },
  { id: 'CALM_EXPLAINER', label: '차분하게 설명형' },
  { id: 'EMPATHY_FOCUSED', label: '공감 중심의 소통' },
  { id: 'LOGICAL_PERSUADER', label: '논리적으로 설득형' },

  // 2 협업 성향
  { id: 'LEADERSHIP', label: '리더십 스타일' },
  { id: 'SUPPORTER', label: '서포터형' },
  { id: 'FREE_SPIRIT', label: '자유로운 영혼' },
  { id: 'FEEDBACKER', label: '피드백커' },
  { id: 'CREATIVE_THINKER', label: '기획 아이디어형' },
  { id: 'MOTIVATED', label: '추진력 넘치는' },
  { id: 'DATA_DRIVEN', label: '데이터 중심적' },
  { id: 'TEAMWORK_FOCUSED', label: '팀워크 중시형' },
  { id: 'DETAIL_ORIENTED', label: '디테일 집착형' },
  { id: 'FLEXIBLE_SOLVER', label: '유연한 문제 해결자' },

  // 3 일하는 방식
  { id: 'GOAL_ORIENTED', label: '목표 지향적' },
  { id: 'PUNCTUAL', label: '시간 엄수형' },
  { id: 'FLEXIBLE_WORKING', label: '유연 근무 가능형' },
  { id: 'MULTI_TASKER', label: '멀티태스킹 능력자' },
  { id: 'FOCUSED', label: '집중 몰입형' },
  { id: 'THOROUGH_PLANNER', label: '철저한 계획형' },
  { id: 'IMPROVISER', label: '즉흥적으로 해결형' },
  { id: 'DETAIL_CHECKER', label: '꼼꼼한 점검형' },
  { id: 'DEADLINE_LOVER', label: '마감 압박을 즐기는' },
  { id: 'CREATIVE_EXPERIMENTER', label: '창의적인 실험가' },

  // 4 문제 해결방식
  { id: 'PROACTIVE', label: '적극적인 돌파형' },
  { id: 'STRATEGIC_ANALYST', label: '분석하고 전략적 해결형' },
  { id: 'CREATIVE_INNOVATOR', label: '창의적이고 독창적' },
  { id: 'COLLABORATIVE', label: '협력해서 해결형' },
  { id: 'DATA_DRIVEN_APPROACH', label: '데이터 기반으로 접근' },
  { id: 'DECISIVE', label: '신속하고 결단력 있는' },
  { id: 'PATIENT', label: '차분히 기다리는 스타일' },
  { id: 'EXPERIMENT_AND_REVISE', label: '실험하고 수정 반복형' },
  { id: 'INTUITIVE', label: '직관에 의존하는 스타일' },
  { id: 'OPINION_FOCUSED', label: '의견 조율을 중시하는' },

  // 5 MBTI
  { id: 'ISTJ', label: 'ISTJ' },
  { id: 'ISFJ', label: 'ISFJ' },
  { id: 'INFJ', label: 'INFJ' },
  { id: 'INTJ', label: 'INTJ' },
  { id: 'ISTP', label: 'ISTP' },
  { id: 'ISFP', label: 'ISFP' },
  { id: 'INFP', label: 'INFP' },
  { id: 'INTP', label: 'INTP' },
  { id: 'ESTP', label: 'ESTP' },
  { id: 'ESFP', label: 'ESFP' },
  { id: 'ENFP', label: 'ENFP' },
  { id: 'ENTP', label: 'ENTP' },
  { id: 'ESTJ', label: 'ESTJ' },
  { id: 'ESFJ', label: 'ESFJ' },
  { id: 'ENFJ', label: 'ENFJ' },
  { id: 'ENTJ', label: 'ENTJ' },
  { id: 'UNKNOWN', label: '모름' },
  { id: 'SECRET', label: '비밀' },
];

export const teamPlaySelectedOptionMap: Record<string, string[]> = {
  '1': [
    'CLEAR_AND_CONCISE',
    'OBSERVANT',
    'RELAXED',
    'DYNAMIC',
    'HUMOROUS',
    'SERIOUS_AND_DEEP',
    'FAST_AND_SIMPLE',
    'CALM_EXPLAINER',
    'EMPATHY_FOCUSED',
    'LOGICAL_PERSUADER',
  ],
  '2': [
    'LEADERSHIP',
    'SUPPORTER',
    'FREE_SPIRIT',
    'FEEDBACKER',
    'CREATIVE_THINKER',
    'MOTIVATED',
    'DATA_DRIVEN',
    'TEAMWORK_FOCUSED',
    'DETAIL_ORIENTED',
    'FLEXIBLE_SOLVER',
  ],
  '3': [
    'GOAL_ORIENTED',
    'PUNCTUAL',
    'FLEXIBLE_WORKING',
    'MULTI_TASKER',
    'FOCUSED',
    'THOROUGH_PLANNER',
    'IMPROVISER',
    'DETAIL_CHECKER',
    'DEADLINE_LOVER',
    'CREATIVE_EXPERIMENTER',
  ],
  '4': [
    'PROACTIVE',
    'STRATEGIC_ANALYST',
    'CREATIVE_INNOVATOR',
    'COLLABORATIVE',
    'DATA_DRIVEN_APPROACH',
    'DECISIVE',
    'PATIENT',
    'EXPERIMENT_AND_REVISE',
    'INTUITIVE',
    'OPINION_FOCUSED',
  ],
  '5': [
    'ISTJ',
    'ISFJ',
    'INFJ',
    'INTJ',
    'ISTP',
    'ISFP',
    'INFP',
    'INTP',
    'ESTP',
    'ESFP',
    'ENFP',
    'ENTP',
    'ESTJ',
    'ESFJ',
    'ENFJ',
    'ENTJ',
    'UNKNOWN',
    'SECRET',
  ],
};

