export type CollaborationStyleType =
  | 'LEADERSHIP'
  | 'SUPPORTER'
  | 'FREE_SPIRIT'
  | 'FEEDBACKER'
  | 'CREATIVE_THINKER'
  | 'MOTIVATED'
  | 'DATA_DRIVEN'
  | 'TEAMWORK_FOCUSED'
  | 'DETAIL_ORIENTED'
  | 'FLEXIBLE_SOLVER';
