export type ProblemSolvingApproachType =
  | 'PROACTIVE'
  | 'STRATEGIC_ANALYST'
  | 'CREATIVE_INNOVATOR'
  | 'COLLABORATIVE'
  | 'DATA_DRIVEN_APPROACH'
  | 'DECISIVE'
  | 'PATIENT'
  | 'EXPERIMENT_AND_REVISE'
  | 'INTUITIVE'
  | 'OPINION_FOCUSED';
