export type SidoType =
  | 'SEOUL'
  | 'BUSAN'
  | 'DAEGU'
  | 'INCHEON'
  | 'GWANGJU'
  | 'DAEJEON'
  | 'ULSAN'
  | 'SEJEONG'
  | 'GYEONGGI'
  | 'GANGWON'
  | 'CHUNGCHEONGBUK'
  | 'CHUNGCHEONGNAM'
  | 'JEONBUK'
  | 'JEONLLANAM'
  | 'GYEONGSANGBUK'
  | 'GYEONGSANGNAM'
  | 'JEJU';
