export type WorkStyleType =
  | 'GOAL_ORIENTED'
  | 'PUNCTUAL'
  | 'FLEXIBLE_WORKING'
  | 'MULTI_TASKER'
  | 'FOCUSED'
  | 'THOROUGH_PLANNER'
  | 'IMPROVISER'
  | 'DETAIL_CHECKER'
  | 'DEADLINE_LOVER'
  | 'CREATIVE_EXPERIMENTER';
