import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";
import ContextProvider from "./context";
import Provider from "@/lib/chakra";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Waggle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Provider>
        <ContextProvider>
        <header>
          <Header />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
        </ContextProvider>
        </Provider>
      </body>
    </html>
  );
}
